language: python
python:
  - "3.7.3"
install:
  - pip install pyyaml
  - sudo apt install zip
# command to run tests
script:
  - python buildscript.py
  - zip -r release.zip templates
  - ls -all
deploy:
  provider: releases
  api_key: $GIT_UPLOAD_TOKEN
  file: release.zip
  skip_cleanup: true
  on:
    tags: true